version: '3.8'

services:
  map-search-agent-back:
    build: .
    ports:
      - "8002:8002"
    environment:
      - STACK_TYPE=local
    volumes:
      - ./.env.local:/app/.env.local:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s